" tpp - competitive programming vimrc
" Clean editor config for fast coding

" General
set nocompatible
syntax on
filetype plugin indent on
set encoding=utf-8
set mouse=a

" Indentation
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smartindent
set autoindent

" Display
set number
set ruler
set showcmd
set laststatus=2
set statusline=%F%m%r%h%w
set scrolloff=5

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase

" Performance
set ttyfast
set autoread
set nobackup
set noswapfile
set nowritebackup

" Editing
set backspace=indent,eol,start
set matchpairs+=<:>
set clipboard=unnamed

" Ctrl+S = save
nnoremap <C-s> :w<CR>
inoremap <C-s> <Esc>:w<CR>a

" Ctrl+F = search
nnoremap <C-f> /

" Esc clears search highlights
nnoremap <Esc> :nohlsearch<CR>

" tpp commands (type :test, :run, :build, :prepare)
:command! Test w | !tpp test
:command! -nargs=? Run w | execute '!tpp run' . (<q-args> == '' ? '' : ' ' . <q-args>)
:command! Build w | !tpp build
:command! Prepare w | !tpp prepare
:command! Add !tpp add

cnoreabbrev test Test
cnoreabbrev run Run
cnoreabbrev build Build
cnoreabbrev prepare Prepare
cnoreabbrev add Add

" File commands (type :in 1, :out 2, :exp 1)
" Opens file in external editor, returns to code when done.
:command! -nargs=? In w | execute '!tpp in ' . (<q-args> == '' ? '1' : <q-args>)
:command! -nargs=? Out w | execute '!tpp out ' . (<q-args> == '' ? '1' : <q-args>)
:command! -nargs=? Exp w | execute '!tpp exp ' . (<q-args> == '' ? '1' : <q-args>)
:command! -nargs=? Dif execute '!tpp dif ' . (<q-args> == '' ? '' : <q-args>)

cnoreabbrev in In
cnoreabbrev out Out
cnoreabbrev exp Exp
cnoreabbrev dif Dif
