" Set compatibility to Vim only.
set nocompatible

" Helps force plug-ins to load correctly when it is turned back on below.
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin '907th/vim-auto-save'
call vundle#end()

" Turn on syntax highlighting.
syntax on

" For plug-ins to load correctly.
filetype plugin indent on

" Turn off modelines
set modelines=0

" Automatically wrap text that extends beyond the screen length.
set wrap

" Uncomment below to set the max textwidth. Use a value corresponding to the width of your screen.
" set textwidth=79
set formatoptions=tcqrn1
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround

" Display 5 lines above/below the cursor when scrolling with a mouse.
set scrolloff=5
" Fixes common backspace problems
set backspace=indent,eol,start

" Speed up scrolling in Vim
set ttyfast

" Status bar
set laststatus=2

" Display options
set showmode
set showcmd

" Highlight matching pairs of brackets. Use the '%' character to jump between them.
set matchpairs+=<:>

" Show line numbers
set number

" Set status line display
" set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ [BUFFER=%n]\ %{strftime('%c')}
set statusline=%F%m%r%h%w

" Encoding
set encoding=utf-8

" Highlight matching search patterns
set hlsearch

" Enable incremental search
set incsearch

" Reload content
set autoread

" Optional

" Enable AutoSave
" let g:auto_save = 1

" Disable beep on errors
" set noerrorbells

" Enable mouse for scrolling and resizing
" set mouse=a

" Functions
:function SaveChanges()
:  execute 'write'
:endfunction

:function QuitCode()
:  execute 'qall'
:endfunction

" Map
nnoremap e <c-w>k " Up
nnoremap d <c-w>j " Right
nnoremap s <c-w>h " Left
nnoremap f <c-w>l " Down

nnoremap q :qall <CR> " Quit all windows
nnoremap w :write <CR> " Save window

:command -nargs=0 Q :call QuitCode() " Quit all windows
:command -nargs=0 W :call SaveChanges() " Save window


